- hosts: all
  become: yes
  tasks:
    - name: install yum-utils
      yum:
        name: yum-utils
        state: present
        update_cache: true
    - name: install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: present
        update_cache: true
    - name: install lvm2
      yum:
        name: lvm2
        state: present
        update_cache: true
    - name: Import Docker CE repository gpg key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present
    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        force: yes
        owner: root
        group: root
        mode: 0644
    - name: Install Docker CE
      yum:
        name: docker-ce
        state: present
        update_cache: yes
    - name: Update dependencies
      yum:
        name: '*'
        state: latest
    - name: start Docker
      service:
        name: docker
        state: started
    - name: disable SELinux
      command: setenforce 0
    - name: disable SELinux on reboot
      selinux:
        state: disabled
    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
    - name: add Kubernetes' YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes
    - name: install kubelet
      yum:
        name: kubelet
        state: present
        update_cache: true
    - name: install kubeadm
      yum:
        name: kubeadm
        state: present
    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        state: started

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl
        state: present
